// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/logout": {
    params: {};
  };
  "/catalog": {
    params: {};
  };
  "/destilados": {
    params: {};
  };
  "/cafe": {
    params: {};
  };
  "/api/lookups/categories": {
    params: {};
  };
  "/api/lookups/grapes": {
    params: {};
  };
  "/api/products/:id": {
    params: {
      "id": string;
    };
  };
  "/api/products/save": {
    params: {};
  };
  "/api/catalog/:catalogType/update-position": {
    params: {
      "catalogType": string;
    };
  };
  "/api/catalog/:catalogType/vaciar-celda": {
    params: {
      "catalogType": string;
    };
  };
  "/api/catalog/:catalogType/create-title": {
    params: {
      "catalogType": string;
    };
  };
  "/api/catalog/:catalogType/update-title": {
    params: {
      "catalogType": string;
    };
  };
  "/api/catalog/:catalogType/delete-title": {
    params: {
      "catalogType": string;
    };
  };
  "/api/catalog/:catalogType/insert-row": {
    params: {
      "catalogType": string;
    };
  };
  "/api/catalog/:catalogType/delete-row": {
    params: {
      "catalogType": string;
    };
  };
  "/api/catalog/:catalogType/delete-last-empty-rows": {
    params: {
      "catalogType": string;
    };
  };
  "/api/catalog/:catalogType/place-unassigned": {
    params: {
      "catalogType": string;
    };
  };
  "/admin/products": {
    params: {};
  };
  "/admin/products/create": {
    params: {};
  };
  "/admin/products/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/admin/products/:id/delete": {
    params: {
      "id": string;
    };
  };
  "/admin/categories": {
    params: {};
  };
  "/admin/categories/create": {
    params: {};
  };
  "/admin/categories/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/admin/categories/:id/delete": {
    params: {
      "id": string;
    };
  };
  "/admin/grape-types": {
    params: {};
  };
  "/admin/grape-types/create": {
    params: {};
  };
  "/admin/grape-types/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/admin/grape-types/:id/delete": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/logout" | "/catalog" | "/destilados" | "/cafe" | "/api/lookups/categories" | "/api/lookups/grapes" | "/api/products/:id" | "/api/products/save" | "/api/catalog/:catalogType/update-position" | "/api/catalog/:catalogType/vaciar-celda" | "/api/catalog/:catalogType/create-title" | "/api/catalog/:catalogType/update-title" | "/api/catalog/:catalogType/delete-title" | "/api/catalog/:catalogType/insert-row" | "/api/catalog/:catalogType/delete-row" | "/api/catalog/:catalogType/delete-last-empty-rows" | "/api/catalog/:catalogType/place-unassigned" | "/admin/products" | "/admin/products/create" | "/admin/products/:id/edit" | "/admin/products/:id/delete" | "/admin/categories" | "/admin/categories/create" | "/admin/categories/:id/edit" | "/admin/categories/:id/delete" | "/admin/grape-types" | "/admin/grape-types/create" | "/admin/grape-types/:id/edit" | "/admin/grape-types/:id/delete";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/logout.tsx": {
    id: "routes/logout";
    page: "/logout";
  };
  "routes/catalog.tsx": {
    id: "routes/catalog";
    page: "/catalog";
  };
  "routes/destilados.tsx": {
    id: "routes/destilados";
    page: "/destilados";
  };
  "routes/cafe.tsx": {
    id: "routes/cafe";
    page: "/cafe";
  };
  "routes/api.lookups.categories.ts": {
    id: "routes/api.lookups.categories";
    page: "/api/lookups/categories";
  };
  "routes/api.lookups.grapes.ts": {
    id: "routes/api.lookups.grapes";
    page: "/api/lookups/grapes";
  };
  "routes/api.products.$id.ts": {
    id: "routes/api.products.$id";
    page: "/api/products/:id";
  };
  "routes/api.products.save.ts": {
    id: "routes/api.products.save";
    page: "/api/products/save";
  };
  "routes/api.catalog.update-position.ts": {
    id: "routes/api.catalog.update-position";
    page: "/api/catalog/:catalogType/update-position";
  };
  "routes/api.catalog.vaciar-celda.ts": {
    id: "routes/api.catalog.vaciar-celda";
    page: "/api/catalog/:catalogType/vaciar-celda";
  };
  "routes/api.catalog.create-title.ts": {
    id: "routes/api.catalog.create-title";
    page: "/api/catalog/:catalogType/create-title";
  };
  "routes/api.catalog.update-title.ts": {
    id: "routes/api.catalog.update-title";
    page: "/api/catalog/:catalogType/update-title";
  };
  "routes/api.catalog.delete-title.ts": {
    id: "routes/api.catalog.delete-title";
    page: "/api/catalog/:catalogType/delete-title";
  };
  "routes/api.catalog.insert-row.ts": {
    id: "routes/api.catalog.insert-row";
    page: "/api/catalog/:catalogType/insert-row";
  };
  "routes/api.catalog.delete-row.ts": {
    id: "routes/api.catalog.delete-row";
    page: "/api/catalog/:catalogType/delete-row";
  };
  "routes/api.catalog.delete-last-empty-rows.ts": {
    id: "routes/api.catalog.delete-last-empty-rows";
    page: "/api/catalog/:catalogType/delete-last-empty-rows";
  };
  "routes/api.catalog.place-unassigned.ts": {
    id: "routes/api.catalog.place-unassigned";
    page: "/api/catalog/:catalogType/place-unassigned";
  };
  "routes/admin/products.tsx": {
    id: "routes/admin/products";
    page: "/admin/products";
  };
  "routes/admin/products.create.tsx": {
    id: "routes/admin/products.create";
    page: "/admin/products/create";
  };
  "routes/admin/products.edit.tsx": {
    id: "routes/admin/products.edit";
    page: "/admin/products/:id/edit";
  };
  "routes/admin/products.delete.tsx": {
    id: "routes/admin/products.delete";
    page: "/admin/products/:id/delete";
  };
  "routes/admin/categories.tsx": {
    id: "routes/admin/categories";
    page: "/admin/categories";
  };
  "routes/admin/categories.create.tsx": {
    id: "routes/admin/categories.create";
    page: "/admin/categories/create";
  };
  "routes/admin/categories.edit.tsx": {
    id: "routes/admin/categories.edit";
    page: "/admin/categories/:id/edit";
  };
  "routes/admin/categories.delete.tsx": {
    id: "routes/admin/categories.delete";
    page: "/admin/categories/:id/delete";
  };
  "routes/admin/grape-types.tsx": {
    id: "routes/admin/grape-types";
    page: "/admin/grape-types";
  };
  "routes/admin/grape-types.create.tsx": {
    id: "routes/admin/grape-types.create";
    page: "/admin/grape-types/create";
  };
  "routes/admin/grape-types.edit.tsx": {
    id: "routes/admin/grape-types.edit";
    page: "/admin/grape-types/:id/edit";
  };
  "routes/admin/grape-types.delete.tsx": {
    id: "routes/admin/grape-types.delete";
    page: "/admin/grape-types/:id/delete";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/logout": typeof import("./app/routes/logout.tsx");
  "routes/catalog": typeof import("./app/routes/catalog.tsx");
  "routes/destilados": typeof import("./app/routes/destilados.tsx");
  "routes/cafe": typeof import("./app/routes/cafe.tsx");
  "routes/api.lookups.categories": typeof import("./app/routes/api.lookups.categories.ts");
  "routes/api.lookups.grapes": typeof import("./app/routes/api.lookups.grapes.ts");
  "routes/api.products.$id": typeof import("./app/routes/api.products.$id.ts");
  "routes/api.products.save": typeof import("./app/routes/api.products.save.ts");
  "routes/api.catalog.update-position": typeof import("./app/routes/api.catalog.update-position.ts");
  "routes/api.catalog.vaciar-celda": typeof import("./app/routes/api.catalog.vaciar-celda.ts");
  "routes/api.catalog.create-title": typeof import("./app/routes/api.catalog.create-title.ts");
  "routes/api.catalog.update-title": typeof import("./app/routes/api.catalog.update-title.ts");
  "routes/api.catalog.delete-title": typeof import("./app/routes/api.catalog.delete-title.ts");
  "routes/api.catalog.insert-row": typeof import("./app/routes/api.catalog.insert-row.ts");
  "routes/api.catalog.delete-row": typeof import("./app/routes/api.catalog.delete-row.ts");
  "routes/api.catalog.delete-last-empty-rows": typeof import("./app/routes/api.catalog.delete-last-empty-rows.ts");
  "routes/api.catalog.place-unassigned": typeof import("./app/routes/api.catalog.place-unassigned.ts");
  "routes/admin/products": typeof import("./app/routes/admin/products.tsx");
  "routes/admin/products.create": typeof import("./app/routes/admin/products.create.tsx");
  "routes/admin/products.edit": typeof import("./app/routes/admin/products.edit.tsx");
  "routes/admin/products.delete": typeof import("./app/routes/admin/products.delete.tsx");
  "routes/admin/categories": typeof import("./app/routes/admin/categories.tsx");
  "routes/admin/categories.create": typeof import("./app/routes/admin/categories.create.tsx");
  "routes/admin/categories.edit": typeof import("./app/routes/admin/categories.edit.tsx");
  "routes/admin/categories.delete": typeof import("./app/routes/admin/categories.delete.tsx");
  "routes/admin/grape-types": typeof import("./app/routes/admin/grape-types.tsx");
  "routes/admin/grape-types.create": typeof import("./app/routes/admin/grape-types.create.tsx");
  "routes/admin/grape-types.edit": typeof import("./app/routes/admin/grape-types.edit.tsx");
  "routes/admin/grape-types.delete": typeof import("./app/routes/admin/grape-types.delete.tsx");
};